sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 9e-5 128 3 "Hyperparameter experiment 1" ParHyperB1
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 5e-5 128 2 "Hyperparameter experiment 1" ParHyperB2
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 1e-5 256 2 "Hyperparameter experiment 1" ParHyperB3
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 1e-5 128 3 "Hyperparameter experiment 1" ParHyperB4
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 5e-5 64 4 "Hyperparameter experiment 1" ParHyperB5
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 5e-5 256 4 "Hyperparameter experiment 1" ParHyperB6
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 5e-5 64 4 "Hyperparameter experiment 1" ParHyperB7
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 5e-5 64 3 "Hyperparameter experiment 1" ParHyperB8
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 9e-5 64 4 "Hyperparameter experiment 1" ParHyperB9
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 9e-5 192 4 "Hyperparameter experiment 1" ParHyperB10
