sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 1e-5 192 4 "Hyperparameter experiment 1" ParHyper1
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 9e-5 192 2 "Hyperparameter experiment 1" ParHyper2
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 9e-5 256 4 "Hyperparameter experiment 1" ParHyper3
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 5e-5 256 4 "Hyperparameter experiment 1" ParHyper4
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 9e-5 128 3 "Hyperparameter experiment 1" ParHyper5
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 5e-5 128 4 "Hyperparameter experiment 1" ParHyper6
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 1e-5 128 4 "Hyperparameter experiment 1" ParHyper7
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 5e-5 64 4 "Hyperparameter experiment 1" ParHyper8
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 9e-5 192 4 "Hyperparameter experiment 1" ParHyper9
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 5e-5 256 3 "Hyperparameter experiment 1" ParHyper10
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 5e-5 128 4 "Hyperparameter experiment 1" ParHyper11
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 5e-5 256 3 "Hyperparameter experiment 1" ParHyper12
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 1e-5 192 3 "Hyperparameter experiment 1" ParHyper13
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 5e-5 128 2 "Hyperparameter experiment 1" ParHyper14
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 9e-5 128 2 "Hyperparameter experiment 1" ParHyper15
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 1e-5 64 2 "Hyperparameter experiment 1" ParHyper16
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 9e-5 256 3 "Hyperparameter experiment 1" ParHyper17
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 1e-5 128 2 "Hyperparameter experiment 1" ParHyper18
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 5e-5 128 2 "Hyperparameter experiment 1" ParHyper19
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 9e-5 256 2 "Hyperparameter experiment 1" ParHyper20
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 5e-5 128 3 "Hyperparameter experiment 1" ParHyper21
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 9e-5 128 4 "Hyperparameter experiment 1" ParHyper22
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 5e-5 192 2 "Hyperparameter experiment 1" ParHyper23
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 9e-5 64 4 "Hyperparameter experiment 1" ParHyper24
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 9e-5 192 4 "Hyperparameter experiment 1" ParHyper25
