sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_v1.0_pubmed_pmc 128 5e-4 192 3 "Hyperparameter experiment 1" ParHyper1
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 16 5e-5 64 2 "Hyperparameter experiment 1" ParHyper2
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 128 5e-6 32 1 "Hyperparameter experiment 1" ParHyper3
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 5e-6 192 2 "Hyperparameter experiment 1" ParHyper4
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 5e-6 32 1 "Hyperparameter experiment 1" ParHyper5
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 128 5e-5 192 2 "Hyperparameter experiment 1" ParHyper6
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 64 5e-5 192 3 "Hyperparameter experiment 1" ParHyper7
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 5e-5 192 4 "Hyperparameter experiment 1" ParHyper8
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_v1.0_pubmed_pmc 64 5e-5 192 3 "Hyperparameter experiment 1" ParHyper9
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 2 5e-4 64 3 "Hyperparameter experiment 1" ParHyper10
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 128 5e-6 128 3 "Hyperparameter experiment 1" ParHyper11
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 32 5e-5 64 4 "Hyperparameter experiment 1" ParHyper12
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_v1.0_pubmed_pmc 64 5e-5 64 3 "Hyperparameter experiment 1" ParHyper13
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 128 5e-6 256 3 "Hyperparameter experiment 1" ParHyper14
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_v1.0_pubmed_pmc 4 5e-6 128 2 "Hyperparameter experiment 1" ParHyper15
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 5e-4 64 3 "Hyperparameter experiment 1" ParHyper16
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 5e-4 32 1 "Hyperparameter experiment 1" ParHyper17
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 64 5e-5 32 1 "Hyperparameter experiment 1" ParHyper18
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 5e-6 192 2 "Hyperparameter experiment 1" ParHyper19
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_v1.0_pubmed_pmc 32 5e-5 256 4 "Hyperparameter experiment 1" ParHyper20
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_v1.0_pubmed_pmc 64 5e-5 256 4 "Hyperparameter experiment 1" ParHyper21
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 64 5e-5 64 1 "Hyperparameter experiment 1" ParHyper22
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 8 5e-6 192 3 "Hyperparameter experiment 1" ParHyper23
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_large 4 5e-4 128 3 "Hyperparameter experiment 1" ParHyper24
sbatch scripts/slurm-run.sh scripts/run-bc2gm.sh data/bc2gm-corpus/combined-data/conll-narrow/ /scratch/project_2001426/models/biobert_v1.0_pubmed_pmc 16 5e-5 256 1 "Hyperparameter experiment 1" ParHyper25
